export const AVAILABLE_CURRENCIES = {
  AFN: { code: 'AFN', name: 'Afghan Afghani', isoCode: 971 },
  ALL: { code: 'ALL', name: 'Albanian Lek', isoCode: 8 },
  DZD: { code: 'DZD', name: 'Algerian Dinar', isoCode: 12 },
  ARS: { code: 'ARS', name: 'Argentine Peso', isoCode: 32 },
  AMD: { code: 'AMD', name: 'Armenian Dram', isoCode: 51 },
  AUD: { code: 'AUD', name: 'Australian Dollar', isoCode: 36 },
  AZN: { code: 'AZN', name: 'Azerbaijani Manat', isoCode: 944 },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', isoCode: 48 },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', isoCode: 50 },
  BYN: { code: 'BYN', name: 'Belarusian Ruble', isoCode: 933 },
  BOB: { code: 'BOB', name: 'Bolivian Boliviano', isoCode: 68 },
  BWP: { code: 'BWP', name: 'Botswana Pula', isoCode: 72 },
  BRL: { code: 'BRL', name: 'Brazilian Real', isoCode: 986 },
  BND: { code: 'BND', name: 'Brunei Dollar', isoCode: 96 },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', isoCode: 975 },
  BIF: { code: 'BIF', name: 'Burundian Franc', isoCode: 108 },
  KHR: { code: 'KHR', name: 'Cambodian Riel', isoCode: 116 },
  CAD: { code: 'CAD', name: 'Canadian Dollar', isoCode: 124 },
  XOF: { code: 'XOF', name: 'CFA Franc BCEAO', isoCode: 952 },
  XAF: { code: 'XAF', name: 'CFA Franc BEAC', isoCode: 950 },
  CLP: { code: 'CLP', name: 'Chilean Peso', isoCode: 152 },
  CNY: { code: 'CNY', name: 'Chinese Yuan', isoCode: 156 },
  COP: { code: 'COP', name: 'Colombian Peso', isoCode: 170 },
  CDF: { code: 'CDF', name: 'Congolese Franc', isoCode: 976 },
  CRC: { code: 'CRC', name: 'Costa Rican Colón', isoCode: 188 },
  HRK: { code: 'HRK', name: 'Croatian Kuna', isoCode: 191 },
  CUP: { code: 'CUP', name: 'Cuban Peso', isoCode: 192 },
  CZK: { code: 'CZK', name: 'Czech Koruna', isoCode: 203 },
  DKK: { code: 'DKK', name: 'Danish Krone', isoCode: 208 },
  DJF: { code: 'DJF', name: 'Djiboutian Franc', isoCode: 262 },
  EGP: { code: 'EGP', name: 'Egyptian Pound', isoCode: 818 },
  ERN: { code: 'ERN', name: 'Eritrean Nakfa', isoCode: 230 },
  EUR: { code: 'EUR', name: 'Euro', isoCode: 978 },
  GMD: { code: 'GMD', name: 'Gambian Dalasi', isoCode: 270 },
  GEL: { code: 'GEL', name: 'Georgian Lari', isoCode: 981 },
  GHS: { code: 'GHS', name: 'Ghanaian Cedi', isoCode: 936 },
  GNF: { code: 'GNF', name: 'Guinean Franc', isoCode: 324 },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', isoCode: 344 },
  HUF: { code: 'HUF', name: 'Hungarian Forint', isoCode: 348 },
  ISK: { code: 'ISK', name: 'Icelandic Króna', isoCode: 352 },
  INR: { code: 'INR', name: 'Indian Rupee', isoCode: 356 },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', isoCode: 360 },
  IQD: { code: 'IQD', name: 'Iraqi Dinar', isoCode: 368 },
  ILS: { code: 'ILS', name: 'Israeli Shekel', isoCode: 376 },
  JPY: { code: 'JPY', name: 'Japanese Yen', isoCode: 392 },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', isoCode: 400 },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', isoCode: 398 },
  KES: { code: 'KES', name: 'Kenyan Shilling', isoCode: 404 },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', isoCode: 414 },
  AOA: { code: 'AOA', name: 'Kwanza', isoCode: 973 },
  KGS: { code: 'KGS', name: 'Kyrgyzstani Som', isoCode: 417 },
  LAK: { code: 'LAK', name: 'Lao Kip', isoCode: 418 },
  LBP: { code: 'LBP', name: 'Lebanese Pound', isoCode: 422 },
  LYD: { code: 'LYD', name: 'Libyan Dinar', isoCode: 434 },
  MKD: { code: 'MKD', name: 'Macedonian Denar', isoCode: 807 },
  MGA: { code: 'MGA', name: 'Malagasy Ariary', isoCode: 969 },
  MWK: { code: 'MWK', name: 'Malawian Kwacha', isoCode: 454 },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', isoCode: 458 },
  MUR: { code: 'MUR', name: 'Mauritian Rupee', isoCode: 480 },
  MXN: { code: 'MXN', name: 'Mexican Peso', isoCode: 484 },
  MDL: { code: 'MDL', name: 'Moldovan Leu', isoCode: 498 },
  MNT: { code: 'MNT', name: 'Mongolian Tögrög', isoCode: 496 },
  MAD: { code: 'MAD', name: 'Moroccan Dirham', isoCode: 504 },
  MZN: { code: 'MZN', name: 'Mozambican Metical', isoCode: 943 },
  NAD: { code: 'NAD', name: 'Namibian Dollar', isoCode: 516 },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', isoCode: 524 },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', isoCode: 554 },
  NIO: { code: 'NIO', name: 'Nicaraguan Córdoba', isoCode: 558 },
  NGN: { code: 'NGN', name: 'Nigerian Naira', isoCode: 566 },
  NOK: { code: 'NOK', name: 'Norwegian Krone', isoCode: 578 },
  OMR: { code: 'OMR', name: 'Omani Rial', isoCode: 512 },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', isoCode: 586 },
  PYG: { code: 'PYG', name: 'Paraguayan Guaraní', isoCode: 600 },
  PEN: { code: 'PEN', name: 'Peruvian Sol', isoCode: 604 },
  PHP: { code: 'PHP', name: 'Philippine Peso', isoCode: 608 },
  PLN: { code: 'PLN', name: 'Polish Złoty', isoCode: 985 },
  GBP: { code: 'GBP', name: 'Pound Sterling', isoCode: 826 },
  QAR: { code: 'QAR', name: 'Qatari Riyal', isoCode: 634 },
  RON: { code: 'RON', name: 'Romanian Leu', isoCode: 946 },
  SAR: { code: 'SAR', name: 'Saudi Riyal', isoCode: 682 },
  RSD: { code: 'RSD', name: 'Serbian Dinar', isoCode: 941 },
  SCR: { code: 'SCR', name: 'Seychellois Rupee', isoCode: 690 },
  SLL: { code: 'SLL', name: 'Sierra Leonean Leone', isoCode: 694 },
  SGD: { code: 'SGD', name: 'Singapore Dollar', isoCode: 702 },
  SOS: { code: 'SOS', name: 'Somali Shilling', isoCode: 706 },
  ZAR: { code: 'ZAR', name: 'South African Rand', isoCode: 710 },
  KRW: { code: 'KRW', name: 'South Korean Won', isoCode: 410 },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', isoCode: 144 },
  SDG: { code: 'SDG', name: 'Sudanese Pound', isoCode: 938 },
  SRD: { code: 'SRD', name: 'Surinam Dollar', isoCode: 968 },
  SZL: { code: 'SZL', name: 'Swazi Lilangeni', isoCode: 748 },
  SEK: { code: 'SEK', name: 'Swedish Krona', isoCode: 752 },
  CHF: { code: 'CHF', name: 'Swiss Franc', isoCode: 756 },
  TWD: { code: 'TWD', name: 'Taiwan Dollar', isoCode: 901 },
  TJS: { code: 'TJS', name: 'Tajikistani Somoni', isoCode: 972 },
  TZS: { code: 'TZS', name: 'Tanzanian Shilling', isoCode: 834 },
  THB: { code: 'THB', name: 'Thai Baht', isoCode: 764 },
  TND: { code: 'TND', name: 'Tunisian Dinar', isoCode: 788 },
  TRY: { code: 'TRY', name: 'Turkish Lira', isoCode: 949 },
  AED: { code: 'AED', name: 'UAE Dirham', isoCode: 784 },
  UGX: { code: 'UGX', name: 'Ugandan Shilling', isoCode: 800 },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', isoCode: 980 },
  UYU: { code: 'UYU', name: 'Uruguayan Peso', isoCode: 858 },
  USD: { code: 'USD', name: 'US Dollar', isoCode: 840 },
  UZS: { code: 'UZS', name: 'Uzbekistani Som', isoCode: 860 },
  VND: { code: 'VND', name: 'Vietnamese Dong', isoCode: 704 },
  YER: { code: 'YER', name: 'Yemeni Rial', isoCode: 886 },
};
